### ISSUE TITLE
Homebrew is deprecating brew cask install

### ISSUE THREAD

**Issue by webdevotion** [getferdi/website#23]
This works for me without deprecation warnings:

```bash
$ brew install ferdi
==> Downloading https://github.com/getferdi/ferdi/releases/download/v5.5.0/Ferdi-5.5.0.dmg
Already downloaded: /Users/[...]/Library/Caches/Homebrew/downloads/[...]--Ferdi-5.5.0.dmg
==> Installing Cask ferdi
==> Moving App 'Ferdi.app' to '/Applications/Ferdi.app'.
🍺  ferdi was successfully installed!
```

https://github.com/getferdi/website/blob/491fe179ce069c96ca7b74a1507ceac6f383e9e3/src/pages/download.js#L193

**Comment by Dalabad** [comment]
I also just stumbled across this and created a PR https://github.com/getferdi/website/pull/25

**Comment by kytwb** [comment]
@webdevotion @Dalabad merged, thanks!
