### ISSUE TITLE
Ferdi logo looks bad on site

### ISSUE THREAD

**Issue by keunes** [getferdi/website#3]
The new website looks great. Just the logo doesn't probably because it's way too big (should be 2 times actual size I believe). I'm on Firefox 69.0 on Ubuntu 18.04
![afbeelding](https://user-images.githubusercontent.com/11229646/65489152-dd4b0a80-deaa-11e9-9fc5-67657522e86d.png)
![afbeelding](https://user-images.githubusercontent.com/11229646/65489248-0bc8e580-deab-11e9-8525-98be129498d8.png)

**Comment by vantezzen** [comment]
I have now

**Comment by vantezzen** [comment]
I have now downscaled the logo image and added the drop shadow with CSS instead of including it in the image. Does it look better now?

**Comment by keunes** [comment]
Yup, looks much better! Only thing: for the header icon I would decrease the drop-shadow blur-radius to 3.85px (currently 7) to make it proportional to the icon size.
![afbeelding](https://user-images.githubusercontent.com/11229646/65574895-e00f3380-df6e-11e9-93d5-fc8ff4fda26a.png)

**Comment by kytwb** [comment]
@keunes done! 👍
