### ISSUE TITLE
Update features preview asset

### ISSUE THREAD

**Issue by kytwb** [getferdi/website#5]
I have proceeded with renaming the Password Lock feature as such everywhere for consistency as it was a bit inconsistent before (Ferdi Lock, Password Lock, Ferdi Lock password, etc.). One of the bit left is to change the asset below for the website for `Ferdi Lock` to be `Password Lock`:

![Features Preview](https://getferdi.com/static/feature-more-712cbeded7b9d5297fcf955c6675a8da.png)

**Comment by kytwb** [comment]
Do you still have the asset for that image @vantezzen?

**Comment by vantezzen** [comment]
Yes, I should still have the source file
