### ISSUE TITLE
Add quote from press coverage near footer

### ISSUE THREAD

**Issue by kytwb** [getferdi/website#6]
Via https://www.makeuseof.com/tag/best-telegram-desktop-client-apps/

> One of Ferdi’s best features is separated workspaces. You can use the workspaces feature to group together personal, business, and other workspaces across multiple messengers.

> For instance, if you have a bunch of cryptocurrency-focused Telegram and Slack channels, bunch them up into a specific workspace. Family and friend chats? Do the same. It is easy to add additional messenger services, too, including Facebook Messenger, Slack, WhatsApp, Gmail, and more.

**Comment by kytwb** [comment]
Maybe https://www.chip.de/downloads/Ferdi_177453674.html

**Comment by vantezzen** [comment]
Added via 
3b9a75e
