### ISSUE TITLE
Download links broken on getferdi.com

### ISSUE THREAD

**Issue by BeecherNetworks** [getferdi/website#9]
Links to the Windows (both) and Linux downloads on https://getferdi.com/download/ are getting a 404 on GitHub. The links actually look right, but I've tried in both Firefox and Chrome and the result is the same.

While I'm here, what's the difference between **Ferdi-5.4.0.exe** and **Ferdi-Setup-5.4.0.exe**?

**Comment by anditosan** [comment]
I second the bug, the links are broken. Although you can go to the respective trees in github and find the versions you're looking for.

**Comment by vantezzen** [comment]
Sorry, I have been busy the last few days so I couldn't fix it. The download links should now be working again.

**Comment by kytwb** [comment]
@BeecherNetworks regarding your question:

> While I'm here, what's the difference between Ferdi-5.4.0.exe and Ferdi-Setup-5.4.0.exe?

One is a portable app, the other (with `Setup` in the filename) is a regular one:

> Portable applications offer some definite advantages over their traditional counterparts. They’re lightweight, and they allow you to move between computers while taking your apps and settings with you. Here’s why they’re different and why they’re sometimes—but not always—a good choice.

From [What Is a “Portable” App, and Why Does It Matter?](https://www.howtogeek.com/290358/what-is-a-portable-app-and-why-does-it-matter/)

**Comment by BeecherNetworks** [comment]
I figured that out afterwards by trying both, forgot to follow up myself. Might I suggest adding "portable" to the exe to avoid confusion for others. :)
